spring:
  cloud:
    config:
      server:
        #native:
         # search-locations: file:E:\2016\workspace\micro-finger-config
        git:
#          uri: https://github.com/9ban/micro-finger-config.git
          uri: file:/Users/liyi/IdeaProjects/quickorder-config
#          uri: https://github.com/9ban/quickorder-config.git
#  profiles:
#    active: native


server:
  port: 8888